import Head from "next/head"
import { Inter } from "@next/font/google"
import Cropper from "@/components/Cropper"
import style from "@/styles/Pages/Home.module.scss"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.page}>
        <Cropper />
      </main>
    </>
  )
}
